version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      # Use the SSH key you’ve already added in CircleCI
      - add_ssh_keys:
          fingerprints:
            - "YOUR_SSH_KEY_FINGERPRINT"

      - run:
          name: SSH into EC2 and Deploy
          command: |
            ssh -o StrictHostKeyChecking=no ec2-user@$EC2_PUBLIC_DNS \<< 'EOF'
              set -euo pipefail

              echo "✅ Connected to EC2"

              # Install kubectl if missing
              if ! command -v kubectl &> /dev/null; then
                echo "Installing kubectl..."
                curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
                chmod +x kubectl
                sudo mv kubectl /usr/local/bin/
              fi

              # Update kubeconfig using EC2 IAM role
              aws eks update-kubeconfig --region "$AWS_REGION" --name "$EKS_CLUSTER_NAME"

              # (Optional) Pull latest image from ECR
              echo "Logging into ECR..."
              aws ecr get-login-password --region "$AWS_REGION" | \
                docker login --username AWS --password-stdin "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com"

              # Apply deployment
              echo "Deploying application..."
              kubectl apply -f /path/to/deployment.yaml
              kubectl rollout status deployment/webapp
            EOF

workflows:
  deploy-workflow:
    jobs:
      - deploy