version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/base:stable

jobs:
  build_and_push:
    executor: docker-executor
    steps:
      - checkout

      - run:
          name: Install AWS CLI & Docker
          command: |
            sudo apt-get update && sudo apt-get install -y awscli docker.io

      - run:
          name: Login to AWS ECR
          command: |
            aws ecr get-login-password --region $AWS_REGION \
              | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

      - run:
          name: Build & Push Docker Image
          command: |
            docker build -t $ECR_REPO .
            docker tag $ECR_REPO:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:latest
            docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:latest

  deploy_to_ec2:
    machine:
      image: ubuntu-2004:current
    steps:
      - add_ssh_keys:
          fingerprints:
            - "<YOUR_SSH_KEY_FINGERPRINT>"
      - run:
          name: Deploy to EC2
          command: |
            ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST "
              docker pull $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:latest &&
              docker stop myapp || true &&
              docker rm myapp || true &&
              docker run -d --name myapp -p 80:80 $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:latest
            "

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_and_push
      - deploy_to_ec2:
          requires:
            - build_and_push
