version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y awscli gettext
            curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/${K8S_VERSION}/2024-06-05/bin/linux/amd64/kubectl
            chmod +x kubectl
            sudo mv kubectl /usr/local/bin/
            kubectl version --cli

      - run:
          name: Set environment variables
          command: |
            # Ensure all env vars exist
            : "${AWS_ACCOUNT_ID:?AWS_ACCOUNT_ID not set}"
            : "${AWS_REGION:?AWS_REGION not set}"
            : "${ECR_REPO:?ECR_REPO not set}"
            : "${EC2_USER:?EC2_USER not set}"
            : "${EC2_HOST:?EC2_HOST not set}"

            export ECR_REPO=$(echo "${ECR_REPO}" | tr '[:upper:]' '[:lower:]')
            export IMAGE_TAG="${CIRCLE_SHA1}"

            echo "AWS_ACCOUNT_ID=$AWS_ACCOUNT_ID"
            echo "AWS_REGION=$AWS_REGION"
            echo "ECR_REPO=$ECR_REPO"
            echo "IMAGE_TAG=$IMAGE_TAG"

      - run:
          name: Authenticate with AWS ECR
          command: |
            aws ecr get-login-password --region "$AWS_REGION" \
              | docker login --username AWS --password-stdin "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com"

      - run:
          name: Deploy to Kubernetes
          command: |
            envsubst < k8s/deployment.yaml | kubectl apply -f -
            kubectl rollout status deployment/webapp --timeout=300s

workflows:
  deploy-workflow:
    jobs:
      - deploy