version: 2.1
jobs:
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Install kubectl & helm
          command: |
            sudo apt-get update && sudo apt-get install -y jq
            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            chmod +x kubectl && sudo mv kubectl /usr/local/bin/
            curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
            chmod 700 get_helm.sh
            ./get_helm.sh

      - run:
          name: Export environment variables on EC2 via SSH
          command: |
            ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'
              export AWS_ACCOUNT_ID="${AWS_ACCOUNT_ID}"
              export AWS_REGION="${AWS_REGION}"
              export ECR_REPO="${ECR_REPO}"
              export IMAGE_TAG="${CIRCLE_SHA1}"
              export KUBECONFIG="/home/${EC2_USER}/.kube/config"
              echo "Environment variables exported on EC2:"
              echo "  AWS_ACCOUNT_ID=$AWS_ACCOUNT_ID"
              echo "  AWS_REGION=$AWS_REGION"
              echo "  ECR_REPO=$ECR_REPO"
              echo "  IMAGE_TAG=$IMAGE_TAG"
              export KUBECONFIG=~/.kube/config
              kubectl apply -f k8s/deployment.yaml
              kubectl apply -f k8s/service.yaml
            EOF
            

workflows:
  deploy_on_main:
    jobs:
      - deploy