apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: <AWS_ACCOUNT_ID>.dkr.ecr.<AWS_REGION>.amazonaws.com/<ECR_REPO>:<IMAGE_TAG>
          ports:
            - containerPort: 3000
          env:
            # Kubernetes Secret for Bugsnag
            - name: BUGSNAG_API_KEY
              valueFrom:
                secretKeyRef:
                  name: bugsnag-secret
                  key: api-key
            # Optional: other env vars
            - name: NODE_ENV
              value: "production"
            - name: AWS_REGION
              value: "<AWS_REGION>"
