apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}:${IMAGE_TAG}"
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
            - name: BUGSNAG_API_KEY
              valueFrom:
                secretKeyRef:
                  name: webapp-secrets
                  key: BUGSNAG_API_KEY
