apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: <AWS_ACCOUNT_ID>.dkr.ecr.<AWS_REGION>.amazonaws.com/<ECR_REPO>:<IMAGE_TAG>
          ports:
            - containerPort: 80
          env:
            - name: BUGSNAG_API_KEY
              valueFrom:
                secretKeyRef:
                  name: bugsnag-secret
                  key: api-key
            - name: NODE_ENV
              value: "production"
            - name: AWS_REGION
              value: "<AWS_REGION>"
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
spec:
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
